/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconCarbonApps: typeof import('~icons/carbon/apps.jsx')['default']
  const IconCarbonLogoGithub: typeof import('~icons/carbon/logo-github.jsx')['default']
  const IconMdiAccountBox: typeof import('~icons/mdi/account-box.jsx')['default']
}
